#!/bin/sh

# Check if the branch name contains the JIRA issue number in a case-insensitive manner
if ! git rev-parse --abbrev-ref HEAD | grep -iq '[A-Z]{3}-\d{4}' >/dev/null 2>&1; then
  echo "ERROR: Branch name must include a JIRA issue number in the format 'ADP-0000'."
  exit 1
fi
